bolt-foundry/bolt-foundry

.envrc, replit.nix
lol sapling test
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/1)
=> lol sapling test

infra/bff/friends/init.bff.ts, infra/bff/friends/update.bff.ts
Try to stay up to date as much as possible
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/12).
* __->__ #12
* #11
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/12)
=> Try to stay up to date as much as possible

infra/bff/friends/deploy.bff.ts
Create a deploy prep
Summary:
`bff deploy:prep` now lets a user pull the latest (clean) from main, ready for a fresh deploy.
Test Plan:
```
bff deploy:prep
```
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/13)
=> Create a deploy prep

infra/bff/friends/init.bff.ts
Update init back to good?
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/19)
=> Update init back to good?

README.md, flake.nix, infra/bff/friends/init.bff.ts
Fix bff init to work with replit
Summary:
Add some extra config to make things work properly™
Test Plan:
=> Fix bff init to work with replit

.env, .envrc, infra/bff/friends/init.bff.ts, infra/bff/shellBase.ts
Open VSCode automatically
Summary:
MAGIC
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/27)
=> Open VSCode automatically

infra/bff/friends/update.bff.ts, infra/bff/shellBase.ts
Create a deploy script
Summary:
Creates a deploy script which overwrites all changes and resets to the main branch.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/29)
=> Create a deploy script

packages/client/components/MarketingFrame.tsx
Update button to have a computer icon
Summary:
tsia
Test Plan:
(photo)
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/30)
=> Update button to have a computer icon

packages/bfDs/const.tsx, packages/client/pages/MarketingPage.tsx, packages/clientRenderer/BaseComponent.tsx
ENG-17 hide login
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/38).
* __->__ #38
* #37
=> ENG-17 hide login

packages/bfDs/GoogleDriveFilePicker.tsx, packages/client/components/LoginForm.tsx, packages/main.ts
Instead of logging in on the current domain, if the proper args are set, login on the new domain.
Summary:
Closes ENG-23.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/36).
* __->__ #36
* #35
* #34
* #33
=> Instead of logging in on the current domain, if the proper args are set, login on the new domain.

infra/bff/friends/update.bff.ts
Remove deploy from old spot
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/41)
=> Remove deploy from old spot

infra/bff/friends/update.bff.ts
Fix update
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/42)
=> Fix update

infra/bff/friends/commit.bff.ts
Formatting and default values
Summary:
Make it so we don't get caught up if something is bustedish
Test Plan:
=> Formatting and default values

docs/developing-on-replit.md, packages/client/components/MarketingIGHscroll.tsx
updating marketing site to remove video
Summary:
Test Plan:
=> updating marketing site to remove video

infra/bff/friends/commit.bff.ts
Catch error on bff commit
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/48)
=> Catch error on bff commit

packages/client/components/MarketingFrame.tsx
Changes the top login button temporarily
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/49)
=> Changes the top login button temporarily

flake.lock
Upgrade unstable packages
Summary:
Upgrades deno most importantly. Faster LSP!
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/51)
=> Upgrade unstable packages

packages/__generated__/ContactUsSubmitFormMutation.graphql.ts, packages/__generated__/_graphql_imports.ts, packages/__generated__/_nexustypes.ts, packages/bfDs/Demo.tsx, packages/bfDs/Modal.tsx, packages/bfDs/ModalPortal.tsx, packages/bfDs/contexts/BfDsContext.tsx, packages/bfDs/hooks/useBfDs.tsx, packages/client/components/App.tsx, packages/client/components/ContactUs.tsx, packages/graphql/schema.graphql, packages/graphql/types/BfGraphQLContactForm.ts, packages/graphql/types/mod.ts, resources/style.css
Connected graphql mutation to UI
Summary: UI now works with graphql
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/97).
* __->__ #97
* #95
* #84
* #83
=> Connected graphql mutation to UI

packages/graphql/graphql.ts
Add bootcamp task
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/98)
=> Add bootcamp task

packages/client/components/ContactUs.tsx, packages/client/components/MarketingCallToAction.tsx, packages/client/pages/MarketingPage.tsx
Put Contact form on home screen
Summary: added contact form to home screen w. cta buttin that goes to /contact-us. Put inside of marketing frame so it looks prettier and so user can navigate back to home page
Test Plan:
=> Put Contact form on home screen

deps.ts, packages/client/pages/LoginPage.tsx, packages/web/web.ts
Housekeeping items
Summary:
Update the logging format, and other lil fixes.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/117)
=> Housekeeping items

infra/internalbf.com/client/pages/LoginPage.tsx
fix login page issues for internalbf
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/125)
=> fix login page issues for internalbf

infra/internalbf.com/client/components/App.tsx, infra/internalbf.com/client/components/GoogleDriveFilePicker.tsx, infra/internalbf.com/client/components/InternalMediaIngestion.tsx, infra/internalbf.com/client/components/InternalMediaList.tsx, infra/internalbf.com/client/pages/Ingest.tsx, infra/internalbf.com/clientRenderer/BaseComponent.tsx, infra/internalbf.com/resources/style.css, packages/bfDs/static/BfSymbol.tsx, packages/client/components/App.tsx, packages/client/pages/InternalBfDotComPage.tsx, resources/style.css
Initial architecture of the internalBf page
Summary: Built based off of justins designs
Test Plan:
=> Initial architecture of the internalBf page

infra/internalbf.com/client/components/App.tsx
little routing fix
Summary: fixed the route for internal bf so the new page I built can be accessed when logged out at /new. This is just so I can see it when I am working on it
Test Plan:
=> little routing fix

infra/internalbf.com/client/components/InternalMediaList.tsx, packages/bfDs/Table.tsx, packages/bfDs/TableCell.tsx, resources/style.css
Table Component
Summary:
Made a reusable table component w/ @Justin
Test Plan:
=> Table Component

lib/_readme.md, packages/client/lib/_readme.md, packages/lib/_readme.md
Add readme for lib directories
Summary:
Adds three readmes to explain the lib directories and how to know which one to use.
Test Plan:
See how many questions get asked about it.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/113).
* #114
* __->__ #113
=> Add readme for lib directories

infra/internalbf.com/client/components/InternalMediaList.tsx, infra/internalbf.com/client/pages/Ingest.tsx, infra/internalbf.com/clientRenderer/BaseComponent.tsx, infra/internalbf.com/resources/style.css, packages/bfDs/static/BfSymbol.tsx, resources/internalStyle.css, resources/style.css
[internal] tweaks to design
Summary:
Test Plan:
=> [internal] tweaks to design

.gitignore
hide git and sapling from each other
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/137)
=> hide git and sapling from each other

.envrc, packages/client/components/MarketingFrame.tsx
Remove envrc and bring back building
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/139)
=> Remove envrc and bring back building

packages/bfDb/bfDb.ts, packages/bfDb/classes/BfModel.ts
Update BfDb and BfModel
Summary:
Adds queries, fixes saving, and unjankifies props.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/140).
* #141
* __->__ #140
=> Update BfDb and BfModel

packages/web/web.ts
Add duration logging
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/143)
=> Add duration logging

infra/internalbf.com/client/components/App.tsx, infra/internalbf.com/client/components/InternalMediaIngestion.tsx, infra/internalbf.com/client/components/InternalProjectsList.tsx, infra/internalbf.com/client/pages/MediaPage.tsx, infra/internalbf.com/client/pages/ProjectsPage.tsx
Built a projects page
Summary: page found at /projects on internal
Test Plan:
=> Built a projects page

packages/bfDb/bfDb.ts, packages/bfDb/classes/BfAuth.ts, packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/models/BfAccount.ts, packages/bfDb/models/BfNodeJob.ts, packages/bfDb/models/BfOrganization.ts, packages/graphql/types/BfGraphQLCurrentViewer.ts
Fix semantics for owners, targets, creators
Summary:
honestly i'm burnt out and i'm sorry.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/157)
=> Fix semantics for owners, targets, creators

infra/internalbf.com/client/components/InternalHeader.tsx, infra/internalbf.com/client/components/InternalMediaIngestion.tsx, infra/internalbf.com/client/pages/MediaPage.tsx, infra/internalbf.com/client/pages/ProjectsPage.tsx, packages/client/hooks/useIntersectionObserver.ts, resources/internalStyle.css
Made dynamic header
Summary: made a dynamic header with some cool animations w/ Justin
Test Plan:
https://github.com/bolt-foundry/bolt-foundry/assets/87879951/aaea26fb-f770-46a3-b230-4d1b60a37cc3
=> Made dynamic header

infra/bff/friends/commit.bff.ts
Don't goto main on commit
Summary:
tsia
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/161)
=> Don't goto main on commit

experimental/randallb/watcher/ingest.ts, experimental/randallb/watcher/watcher.plist, experimental/randallb/watcher/watcher.ts
New watcher that runs on my computer
Summary:
This automatically ingests files which get put in google, and then creates a project and pings discord.
Test Plan:
https://github.com/bolt-foundry/bolt-foundry/assets/448694/1a5a6853-8e72-453d-9034-53a5fe93b8d3
=> New watcher that runs on my computer

packages/client/components/MarketingFrame.tsx
Example commit
Summary:
woo
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/165)
=> Example commit

infra/internalbf.com/jobRunner/jobRunner.ts, lib/ffmpegInterface.ts
Small job runner updates
Summary:
Louder logging generally, and a tunable temp directory.
Test Plan:
=> Small job runner updates

aws/clientRenderer/main.ts, packages/web/web.ts
Redirect aws routes if not logged in
Summary:
Log in using google to access the system
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/169)
=> Redirect aws routes if not logged in

.envrc
Bring back direnv
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/170)
=> Bring back direnv

aws/clientRenderer/relay-environment.ts, experimental/randallb/watcher/ingest.ts
Change everything to go through boltfoundry.com instead of justin's sandbox
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/173)
=> Change everything to go through boltfoundry.com instead of justin's sandbox

aws/client/lib/BFRenderer.ts, aws/client/lib/encodingTools.ts, infra/build/build.ts
fix the 80% bug
Summary: Large video files were being downloaded every time you download a clip, this cause it to not get audio in time and eventually timeout. This uses the video in the browser to get audio. Instead of waiting for the file to download, now you have to wait for the whole clip to play through, but it is much faster.
Test Plan:
=> fix the 80% bug

aws/vcs/client/compositions/templates/shockcollar.jsx
[fix] shock collar banner timing
Summary:
Test Plan:
=> [fix] shock collar banner timing

aws/client/lib/BFRenderer.ts, aws/client/lib/encodingTools.ts
fix sync issue
Summary:
Test Plan:
=> fix sync issue

packages/client/hooks/featureFlagHooks.ts
fix censoring
Summary:
Test Plan:
=> fix censoring

aws/client/hooks/featureFlagHooks.tsx
fix censoring for real
Summary:
Test Plan:
=> fix censoring for real

.gitmodules
Add vcs to submodules
Summary:
Test Plan:
=> Add vcs to submodules

infra/build/bffEsbuild.ts, infra/build/build.ts
If a graphql tag doesn't have a title then ignore it instead of whining loudly
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/189).
* #190
* __->__ #189
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/189)
=> If a graphql tag doesn't have a title then ignore it instead of whining loudly

.envrc, .gitignore, experimental/randallb/watcher/ingest.ts, experimental/randallb/watcher/watcher.ts, flake.nix
Ingest updates
Summary:
Test Plan:
=> Ingest updates

aws/client/lib/BFRenderer.ts
[cropping] fix cropping
Summary: When cropping more than 50%, the video would scale too much. This fixes it and makes it scale properly
Test Plan:
=> [cropping] fix cropping

flake.nix, infra/bff/friends/deploy.bff.ts
Move Yarn to a buildable package
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/206).
* __->__ #206
* #205
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/206)
=> Move Yarn to a buildable package

infra/bff/friends/deploy.bff.ts
Fix deploy messages so they're clearer
Summary:
Parse output of `sl log` and use it to create a git commit that makes more sense.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/207)
=> Fix deploy messages so they're clearer

deno.jsonc, packages/client/components/MarketingIGHscroll.tsx
Lint and folder fixes
Summary:
Test Plan:
=> Lint and folder fixes

deno.jsonc, infra/bff/friends/deploy.bff.ts
Fixed formatting stuff
Summary:
RB left a few parts out of his formatting thingy.
Test Plan:
=> Fixed formatting stuff

infra/bff/friends/boot.bff.ts
Warm bff cache on boot so things run faster probably™
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/210)
=> Warm bff cache on boot so things run faster probably™

aws/client/components/ClipEdit.tsx, aws/client/components/CropLine.tsx, aws/client/components/ManualCropMenu.tsx, aws/client/components/WordMenu.tsx, resources/aws-style.css
[cropping] make cropping better
Summary: added "edit mode" to switch between text and crop editing, changed the ui for crop, added start time slider, added "delete" crop (refresh after using)
Test Plan:
=> [cropping] make cropping better

experimental/randallb/graphql-for-qc.ts, infra/__generated__/_nexustypes.ts, infra/graphql/schema.graphql, packages/__generated__/_nexustypes.ts, packages/bfDb/bfDb.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/models/BfClip.ts, packages/bfDb/models/BfClipReview.ts, packages/graphql/schema.graphql, packages/graphql/types/BfGraphQLClip.ts, packages/graphql/types/BfGraphQLClipReview.ts, packages/graphql/types/BfGraphQLCurrentViewer.ts, packages/graphql/types/Url.ts, packages/graphql/types/mod.ts, packages/types/settings.ts
GraphQL basics
Summary:
Adds support for connections, bfedge targets and stuff.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/217)
=> GraphQL basics

infra/bff/friends/deploy.bff.ts, packages/bfDb/models/BfClip.ts
fix deploy
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/218)
=> fix deploy

aws/client/lib/BFRenderer.ts
Fix bfrenderer
Summary:
Turns out the font loading is requisite. Add it back in.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/220).
* #221
* __->__ #220
=> Fix bfrenderer

aws/client/components/ClipEdit.tsx, aws/client/components/CropModeWord.tsx, aws/client/components/StickerMenu.tsx, aws/client/components/StickerModeWord.tsx, aws/client/ui_components/DropdownSelector.tsx, packages/bfDb/classes/BfBaseModelIdTypes.ts
[sticker] start of sticker
Summary: George's code, committing to unblock cropping fixes
Test Plan:
=> [sticker] start of sticker

infra/bff/friends/deploy.bff.ts, packages/bfDb/bfDb.ts, packages/bfDb/getCurrentViewer.ts
More reliably parse the output of sapling
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/238).
* __->__ #238
* #237
* #236
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/238)
=> More reliably parse the output of sapling

aws/client/ui_components/DropdownSelector.tsx, packages/bfDs/DropdownSelector.tsx
[bugfix] dropdown direction
Summary: added "bottom" as the default position
Test Plan:
=> [bugfix] dropdown direction

aws/client/components/ClipEdit.tsx
[fix] in/out indexes
Summary:
Test Plan:
=> [fix] in/out indexes

packages/client/components/LoginForm.tsx
Update login form to redirect to /?login=success
Summary:
hack for now to figure out where the actual issue is.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/244)
=> Update login form to redirect to /?login=success

infra/bff/friends/relay.bff.ts, infra/build/bffEsbuild.ts
Fix relay for internalbf
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/246).
* __->__ #246
* #245
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/246)
=> Fix relay for internalbf

infra/internalbf.com/internalbf.com.ts
Infra graphql fix
Summary: Updates handler source for infra graphql import.
Test Plan:
=> Infra graphql fix

aws/client/components/Clip.tsx, aws/client/components/ClipEdit.tsx, aws/client/components/ClipList.tsx, resources/aws-style.css
add numbers to clips
Summary:
Test Plan:
=> add numbers to clips

packages/bfDb/classes/BfAuth.ts
extend login timeout
Summary:
Test Plan:
=> extend login timeout

infra/bff/friends/deploy.bff.ts
update bff deploy
Summary:
Test Plan:
=> update bff deploy

packages/bfDb/deps.ts
Don't error if bucket doesn't exist
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/259)
=> Don't error if bucket doesn't exist

packages/bfDb/deps.ts, packages/bfDb/models/BfClipReview.ts
Update object storage client to check for local bucket
Summary:
Check if the local bucket exists
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/261)
=> Update object storage client to check for local bucket

packages/packages.ts
Fixing sev
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/266)
=> Fixing sev

packages/packages.ts
Make exits more resilliant
Summary:
Lol without event.preventDefault() it still just crashes like normal.
This will prevent sev0s like this weekend.
Test Plan:
=> Make exits more resilliant

aws/client/components/DownloadClip.tsx
fix clip titles
Summary:
Test Plan:
=> fix clip titles

docs/product/product.mdx
Product overview document
Summary:
Starting point so the AI knows what we're trying to do.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/293)
=> Product overview document

infra/__generated__/IBfOrganizationsPageQuery.graphql.ts, infra/__generated__/IBfOrganizationsPage_BfOrganization.graphql.ts, infra/__generated__/_graphql_imports.ts, infra/__generated__/_nexustypes.ts, infra/graphql/deps.ts, infra/graphql/graphql.ts, infra/graphql/schema.graphql, infra/graphql/types/IBfGraphQLOrganization.ts, infra/graphql/types/mod.ts, infra/internalbf.com/client/components/App.tsx, infra/internalbf.com/client/components/IBfFrame.tsx, infra/internalbf.com/client/components/InternalMediaList.tsx, infra/internalbf.com/client/components/InternalProjectsList.tsx, infra/internalbf.com/client/pages/ChangesPage.tsx, infra/internalbf.com/client/pages/IBfOrganizationsPage.tsx, packages/__generated__/_graphql_imports.ts, packages/bfDb/bfDb.ts, packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/getCurrentViewer.ts, packages/bfDb/utils.ts, packages/bfDs/Table.tsx, packages/bfDs/TableCell.tsx, packages/client/pages/InternalBfDotComPage.tsx
Organizations Page
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/298).
* __->__ #298
* #297
=> Organizations Page

infra/internalbf.com/client/components/IBfExpandableHeader.tsx, infra/internalbf.com/client/components/IBfFrame.tsx, infra/internalbf.com/client/components/IBfHeader.tsx, infra/internalbf.com/client/components/InternalMediaIngestion.tsx, infra/internalbf.com/client/pages/IBfDashboardPage.tsx, resources/internalStyle.css
[ibf] header
Summary:
Test Plan:
=> [ibf] header

aws/client/lib/encodingTools.ts
Change encoding bitrate to 7mbps instead of 2
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/303)
=> Change encoding bitrate to 7mbps instead of 2

infra/__generated__/_nexustypes.ts, infra/graphql/graphql.ts, infra/graphql/schema.graphql, infra/graphql/types/IBfGraphQLCurrentViewer.ts, infra/graphql/types/IBfGraphQLOrganization.ts, infra/graphql/types/mod.ts, infra/internalbf.com/jobRunner/jobRunner.ts, infra/lib/jupyterUtils.ts, packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/utils.ts
fix internalbf
Summary:
Include the right file in the schema, also rename the user to IBfCurrentViewerInternalAdmin and omni to IBfCurrentViewerIntetrnalAdminOmni.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/304)
=> fix internalbf

infra/bff/friends/deploy.bff.ts
Rename bff deploy to bff land
Summary:
tsia
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/305)
=> Rename bff deploy to bff land

packages/bfDb/classes/BfModel.ts
Fix bfmodel
Summary:
bad find and replace lol
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/307)
=> Fix bfmodel

packages/bfDs/BfDsForm.tsx, packages/bfDs/Input.tsx
Add BFDS components to bfds form
Summary:
Test Plan:
=> Add BFDS components to bfds form

packages/client/components/App.tsx, packages/client/components/ComingSoonHero.tsx, packages/client/pages/ComingSoonPage.tsx
Coming soon hero
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/312)
=> Coming soon hero

infra/aiPlayground/langchainAPI.ts, infra/internalbf.com/client/pages/PlaygroundPage.tsx, packages/bfDs/BfDsForm.tsx, packages/bfDs/Pill.tsx, packages/client/components/App.tsx, packages/client/components/clipsearch/.Sidebar.tsx.788046026~, packages/client/components/clipsearch/Clip.tsx, packages/client/components/clipsearch/ClipsView.tsx, packages/client/components/clipsearch/Nux.tsx, packages/client/components/clipsearch/Search.tsx, packages/client/components/clipsearch/Sidebar.tsx, packages/client/components/clipsearch/fakeData/aiResponse.json, packages/client/pages/ClipSearchPage.tsx, packages/clientRenderer/BaseComponent.tsx, resources/clipSearchStyle.css, resources/style.css
Beautify UI
Summary: Built initial UI for new product with justin. Heavily based on the old word
Test Plan:
=> Beautify UI

infra/bff/friends/populate.bff.ts, packages/bfDb/classes/BfCurrentViewer.ts
Summary: bff populate populates db with transcripts
also updated IBfCurrentViewerInternalAdminOmni to allow custom org id
Test Plan:
=> [bff] add `bff populate`

packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/models/BfMedia.ts, packages/bfDb/models/BfMediaTranscript.ts
=> requested changes

.envrc
=> fix jupyter install

infra/internalbf.com/internalbf.com.ts, infra/watcher/googleDriveWatcher.ts, infra/watcher/ingest.ts
Summary: Adds a basic start for supporting Google Drive Web Hooks. Changes are isolated so they currently don't effect anything else.
Test Plan: 🦧
=> Start of Google Webhooks Support

.gitignore, experimental/george136/promptPlayground.ipynb, infra/jupyter/jupyter_config.py, packages/bfDs/Pill.tsx, packages/client/components/clipsearch/Clip.tsx, packages/client/components/clipsearch/ClipsView.tsx, packages/client/components/clipsearch/Search.tsx, packages/lib/langchain.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/387).
* __->__ #387
* #386
* #385
=> add structured output to langchain

infra/internalbf.com/internalbf.com.ts, packages/bfDb/models/BfNotificationSubscription.ts, packages/ingest/googleDriveNotificationHandler.ts, packages/web/web.ts
Summary: I'm just trying to commit my half-baked changes for my own personal sanity. Changes should be isolated.
Test Plan: 🦧
=> New Google Web Hook Scaffolding

flake.lock
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/395)
=> Downgrade deno to fix builds

packages/bfDb/classes/BfModel.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/409)
=> Formatting

experimental/randallb/drive-ingest.ipynb, lib/googleDriveApi.ts, lib/googleOauth.ts, packages/bfDb/models/BfGoogleDriveResource.ts, packages/bfDb/models/BfJob.ts, packages/client/pages/BlogPage.tsx, packages/web/web.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/411).
* __->__ #411
* #401
* #400
* #399
* #398
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/411)
=> Make it so bfgids for resources match google resource IDs

infra/bff/friends/commit.bff.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/410)
=> Make sapling open simpler.

import_map.json, infra/bff/friends/render.bff.ts, infra/bff/friends/vcs.bff.ts, infra/rendering/render.sh, packages/bfDb/models/BfMedia.ts, packages/graphql/types/BfGraphQLClip.ts, packages/vcs/cli-render/bf-vcscut-tools/bf-vcsrender.zx.mjs, packages/vcs/cli-render/bf-vcscut-tools/install_and_build_vcsrender.sh
Summary: copies an existing video file instead of actual file and creates the transcript file
Test Plan:
=> create files for `bff render`

lib/notionApi.ts
Summary: Adds two incomplete methods to the Notion API. Still working on data formatting, but wanted to commit what I have so far.
Test Plan: 🦧
=> Add two methods to Notion API

infra/bff/friends/hello_world.bff.ts
Summary: Add a Hello World to bff to acclimate one's self with its basic workings.
Test Plan: TBD
=> Initial commit: Hello world

packages/client/components/App.tsx
=> /clip-search to /search

infra/__generated__/_nexustypes.ts, infra/graphql/schema.graphql, infra/rendering/render.sh, packages/__generated__/DownloadClipButtonDownloadMutation.graphql.ts, packages/__generated__/_nexustypes.ts, packages/bfDb/models/BfMedia.ts, packages/client/components/clipsearch/Clip.tsx, packages/client/components/clipsearch/DownloadClipButton.tsx, packages/graphql/schema.graphql, packages/graphql/types/BfGraphQLClip.ts, packages/lib/textUtils.ts, packages/web/web.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/431).
* __->__ #431
* #430
* #429
=> fix server so it downloads mp4

packages/client/components/App.tsx, packages/client/components/clipsearch/ClipsView.tsx
Summary: made search only acessable when logged in and fixed a tweaked the conditional rendering of the google auth thing
Test Plan:
=> nux on authed fix

packages/client/pages/ClipSearchPage.tsx
Summary: settings button on /search navigates to /settings
Test Plan:
=> settings to "/settings"

infra/internalbf.com/client/components/IBfFrame.tsx, infra/internalbf.com/client/pages/ChangesPage.tsx, infra/internalbf.com/client/pages/QcPage.tsx, infra/internalbf.com/client/pages/RandallPlaygroundPage.tsx, packages/bfDs/BfDsButton.tsx, packages/bfDs/BfDsIcon.tsx, packages/bfDs/ButtonConfirmation.tsx, packages/bfDs/Demo.tsx, packages/bfDs/List.tsx, packages/bfDs/ListItem.tsx, packages/bfDs/Tooltip.tsx, packages/client/components/MarketingIGHscroll.tsx, packages/client/components/TopNav.tsx, packages/client/components/VideoPlayer.tsx
Summary: change refs of Icon to BfDsIcon so that traversing the dom with react dev tools is easier to do
Test Plan:
=> change icon to bfdsicon

packages/client/components/ContactUs.tsx, packages/client/pages/ComingSoonPage.tsx, packages/graphql/types/BfGraphQLContactForm.ts
Summary:  contact form is hooked up to notion db and cta and contact form are on home page
Test Plan:
=> Add Cta and contact form

infra/internalbf.com/client/components/InternalMediaList.tsx, infra/internalbf.com/client/components/InternalProjectsList.tsx, infra/internalbf.com/client/pages/ChangesPage.tsx, infra/internalbf.com/client/pages/ClipChangesPage.tsx, infra/internalbf.com/client/pages/IBfOrganizationsPage.tsx, packages/bfDs/BfDsTable.tsx, packages/bfDs/BfDsTableCell.tsx, packages/client/components/settings/Media.tsx, packages/client/components/settings/WatchFolderList.tsx
Summary: change refs of Table to BfDsTable so that traversing the dom with react dev tools is easier to do
Test Plan: TBD
=> ui views: Table -> BfDsTable

infra/internalbf.com/client/pages/QcPage.tsx, infra/internalbf.com/client/pages/RandallPlaygroundPage.tsx, packages/bfDs/BfDsButton.tsx, packages/bfDs/BfDsTooltip.tsx, packages/bfDs/DropdownSelector.tsx, packages/bfDs/Password.tsx, packages/client/components/TopNav.tsx, packages/client/components/UserProfile.tsx, packages/client/components/clipsearch/Clip.tsx
=> bfds components -> "Tooltip" -> "BfDsTooltip" (and its friends)

packages/__generated__/ClipSearchPageQuery.graphql.ts, packages/client/components/clipsearch/ClipsView.tsx, packages/client/components/clipsearch/ClipsViewNullState.tsx, packages/client/components/clipsearch/Nux.tsx, packages/client/components/clipsearch/Search.tsx, packages/client/components/clipsearch/UserList.tsx, packages/client/components/settings/WatchFolderList.tsx, packages/client/pages/ClipSearchPage.tsx
=> Null State update

packages/client/components/LoginForm.tsx
=> successfull login redirects to /search

packages/client/pages/SettingsPage.tsx
=> Settings links to clipsearch

packages/bfDb/models/BfMedia.ts, packages/client/components/clipsearch/DownloadClipButton.tsx, packages/graphql/types/BfGraphQLClip.ts
=> Throwing errors on render failure

packages/bfDs/BfDsTextArea.tsx, packages/client/components/ContactUs.tsx
Summary: TextArea -> BfDsTextArea
Test Plan:
=> TextArea -> BfDsTextArea

experimental/randallb/drive-ingest.ipynb, lib/googleDriveApi.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/models/BfGoogleDriveResource.ts, packages/bfDb/models/BfJob.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/471).
* __->__ #471
* #470
* #469
* #468
* #467
* #466
* #465
* #464
* #463
* #462
=> Specific files in nb

infra/internalbf.com/client/pages/PlaygroundPage.tsx, packages/bfDs/BfDsForm.tsx, packages/bfDs/BfDsInput.tsx, packages/bfDs/Demo.tsx, packages/bfDs/Password.tsx, packages/client/components/ContactUs.tsx, packages/client/components/SettingsForm.tsx, packages/client/components/clipsearch/Search.tsx, packages/client/pages/ResetPasswordPage.tsx
Summary: refactoring userland views: Input -> BfDsInput (fixed history version)
(also includes a fix to a typo in a previous commit that slipped through)
Test Plan:
=> refactoring userland views: Input -> BfDsInput (fixed history version)

infra/internalbf.com/client/Client.tsx, infra/internalbf.com/client/pages/LoginPage.tsx, packages/bfDs/BfDsButton.tsx, packages/bfDs/BfDsInput.tsx, packages/bfDs/BfDsSpinner.tsx, packages/bfDs/BfDsTooltip.tsx, packages/bfDs/Demo.tsx, packages/client/Client.tsx, packages/client/components/PageFrame.tsx, packages/client/components/clipsearch/ClipsView.tsx, packages/client/components/settings/Media.tsx, packages/client/components/settings/WatchFolder.tsx, packages/client/components/settings/WatchFolderList.tsx, packages/client/pages/LoginPage.tsx, packages/client/pages/SettingsPage.tsx
Summary: Spinner -> BfDsSpinner
Test Plan:
=> Spinner -> BfDsSpinner

packages/bfDs/BfDsPassword.tsx, packages/client/pages/ResetPasswordPage.tsx
Summary: Password -> BfDsPassword
Test Plan:
=> Password -> BfDsPassword

packages/bfDs/ListItem.tsx, packages/bfDs/contexts/BfDsContext.tsx, packages/client/contexts/AppStateContext.tsx, packages/client/pages/SettingsPage.tsx, packages/clientRenderer/BaseComponent.tsx
Summary: update ListItem with switch, enable dark mode in settings
Test Plan:
=> add dark mode switch

packages/bfDs/BfDsToast.tsx, packages/bfDs/contexts/BfDsContext.tsx
Summary: Toast-> BfDsToast
Test Plan:
=> Toast-> BfDsToast

infra/bff/friends/ci.bff.ts, infra/build/slimBuild.ts, infra/build/slimRelay.ts, packages/client/pages/BlogPage.tsx
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/513)
=> *actually* enforce formatting

experimental/randallb/drive-ingest.ipynb, infra/jobRunner/jobRunner.ts, packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/models/BfGoogleDriveResource.ts, packages/bfDb/models/BfJob.ts, packages/bfDb/models/BfMedia.ts, packages/bfDb/models/BfMediaAudio.ts, packages/bfDb/models/BfMediaTranscript.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/486).
* __->__ #486
* #512
* #511
* #510
* #509
* #508
=> second draft of ingestion

infra/bff/friends/land.bff.ts
=> Make lands delete the node_modules folder b/c it's symlinked incorrectly

infra/bff/friends/transcribe.bff.ts, packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/coreModels/BfNode.ts
=> add createTargetNode

deno.jsonc, infra/bff/friends/land.bff.ts
False positive
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/527).
* __->__ #527
* #526
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/527)
=> Don't format checkpoints

packages/clientRenderer/BaseComponent.tsx, packages/clientRenderer/clientRenderer.ts
=> Posthog integration and BaseComponent updates

.replitignore
=> add replitignore file and ignore vcs cache

node_modules/posthog-node, packages/__generated__/SetUpMeetingSubmitFormMutation.graphql.ts, packages/client/components/App.tsx, packages/client/components/LandingPageClipCollection.tsx, packages/client/components/LandingPageHero.tsx, packages/client/components/LandingPageMission.tsx, packages/client/components/LandingPageSetUpMeeting.tsx, packages/client/components/LandingPageTestimonials.tsx, packages/client/components/SetUpMeeting.tsx, packages/client/pages/LandingPage.tsx, resources/style.css
Summary: Basic start for marketing page. Needs styling to be refactored. I will try to do this myself ASAP. Now requires logged in.
Test Plan:
=> Marketing Page Fixes @Justicart

packages/bfDs/BfDsModal.tsx, packages/client/hooks/useClickOutside.ts, packages/clientRenderer/BaseComponent.tsx, resources/style.css
=> fix click outside

packages/bfDs/static/BfSymbol.tsx
=> fix stopColor error

packages/client/components/LandingPageHero.tsx, packages/client/components/LandingPageMission.tsx, packages/client/components/LandingPageSetUpMeeting.tsx, packages/client/pages/LandingPage.tsx, resources/style.css
Change all Contact us and Book a meeting links to open the hubspot calendar in a new tab.
Also includes a very minor css change. More will come with a later refactor.
=> Landing page Hubspot link integration.

.github/workflows/nix-github-actions.yml
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/561)
=> require checks on main

.github/workflows/nix-github-actions.yml
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/562)
=> remove push check

infra/bff/friends/boot.bff.ts, infra/bff/friends/build.bff.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/563)
=> rm places where we rm node modules

experimental/randallb/accounts.ipynb, packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/models/BfOrganization.ts, packages/bfDb/utils.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/574).
* __->__ #574
* #573
* #572
* #571
=> Notebook for accounts work

packages/client/components/LandingPageClipCollection.tsx, resources/style.css
Mostly focuses on behavior of the clip collection as viewport size changes with some other optimizations.
=> Marketing Site Responsiveness

infra/__generated__/_nexustypes.ts, infra/graphql/schema.graphql, lib/notionApi.ts, packages/__generated__/BlogPagePostQuery.graphql.ts, packages/__generated__/BlogPageQuery.graphql.ts, packages/__generated__/_nexustypes.ts, packages/client/pages/BlogPage.tsx, packages/graphql/schema.graphql, packages/graphql/types/GraphQLBlog.ts, packages/lib/textUtils.ts, resources/style.css
Summary: add text styles, add callout bg colors, add cover image, add author, add date, style list page
Test Plan:
=> blog work [wip]

packages/lib/langchain.ts
=> Added performance logger for searching

packages/client/components/ComingSoonHero.tsx
"no editors required" -> "we make it easy"
Summary:
Test Plan:
=> Live Marketing Site Hero Tweak

experimental/george136/VectorDb.ipynb
=> jupyter pineconedb notebook

packages/bfDb/coreModels/BfEdge.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/602)
=> Fix bfedge issue

.gitignore, infra/bff/friends/nix.bff.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/617)
=> Change location of nix build system

packages/client/components/LandingPageHero.tsx, packages/client/components/LandingPageMission.tsx, packages/client/components/LandingPageSetUpMeeting.tsx
Rendered text changes only
https://www.notion.so/boltfoundry/Copy-changes-99531664905d47cb85aaf75e6ee92dc2
=> Landing Page Copy Changes

packages/client/components/LandingPageHero.tsx, packages/client/components/LandingPageSetUpMeeting.tsx, packages/client/pages/LandingPage.tsx, resources/style.css
Oversight and mostly by Justin
=> Landing page style changes

packages/client/components/FeatureFlag.tsx, packages/client/components/Hud.tsx, packages/client/pages/LandingPage.tsx
Summary: hide hero videos on marketing site, add `fallback` prop to feature flag
Test Plan:
=> hide hero videos

packages/bfDs/BfDsGlimmer.tsx, packages/bfDs/BfDsSpinner.tsx, packages/client/Client.tsx, packages/client/components/clipsearch/ClipsView.tsx, packages/client/components/clipsearch/ClipsViewGlimmer.tsx, packages/client/components/settings/WatchFolder.tsx, packages/client/components/settings/WatchFolderList.tsx, packages/client/contexts/RouterContext.tsx, packages/client/pages/ClipSearchPage.tsx, packages/client/pages/SettingsPage.tsx, packages/lib/langchain.ts, resources/clipSearchStyle.css
Summary: remove global suspense, fix suspense between page routes
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/624).
* __->__ #624
* #623
* #622
* #621
=> fix suspense

packages/client/components/App.tsx, packages/client/pages/SettingsPage.tsx
=> add routes to settings

packages/client/components/LandingPageClipCollection.tsx, packages/client/pages/LandingPage.tsx
Justin added the videos to s3 which allows this commit to source them for the landing page. He also removed the feature flag which will make them visible again.
=> Bring videos back to the landing page

packages/client/components/LandingPageClipCollection.tsx, resources/style.css
Removes the transparent black gradient on the landing page videos.
=> Remove video gradient on landing page videos.

experimental/randallb/drive-ingest.ipynb, packages/bfDb/bfDb.ts, packages/bfDb/classes/BfModel.ts, packages/bfDb/utils.ts, packages/graphql/types/BfGraphQLNode.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/672).
* __->__ #672
* #670
* #669
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/672)
=> Add cvOrg to my notebook

packages/bfDb/bfDb.ts, packages/bfDb/classes/BfModel.ts, packages/graphql/types/BfGraphQLNode.ts
=> don't try to initialize notifications all the time

infra/__generated__/_nexustypes.ts, infra/graphql/schema.graphql, lib/notionApi.ts, packages/__generated__/BlogPagePostFragment.graphql.ts, packages/__generated__/BlogPageQuery.graphql.ts, packages/__generated__/_nexustypes.ts, packages/client/pages/BlogPage.tsx, packages/graphql/schema.graphql, packages/graphql/types/GraphQLBlog.ts
Links weren't properly formatted before this commit.
=> Fix issue with Notion links

packages/client/components/App.tsx, packages/client/pages/LandingPage.tsx, packages/client/pages/TermsAndPrivacyPage.tsx, resources/style.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/697).
* __->__ #697
* #696
=> Add Terms and Privacy

packages/client/components/LandingPageClipCollection.tsx
=> Use Rubio's podcase clip instead of Pattern's

packages/client/components/LandingPageHero.tsx, packages/client/components/LandingPageMission.tsx, packages/client/pages/LandingPage.tsx, resources/style.css
=> Remove clip collection from landing page

packages/bfDb/bfDb.ts, packages/bfDb/models/BfMediaNodeTranscript.ts, packages/graphql/types/BfGraphQLNode.ts
=> Remove erroneus set levels

deps.ts
=> Fix relative paths in logginig

packages/bfDb/classes/BfModel.ts, packages/bfDb/coreModels/BfEdge.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/714).
* __->__ #714
* #712
=> Touch both sides of an edge when an edge changes

packages/bfDb/models/BfJob.ts
=> Make it so jobs run in a job runner by default

packages/client/components/blog/BlogPageHero.tsx, packages/client/components/blog/BlogPageListItem.tsx, packages/client/components/blog/BlogPostContent.tsx, packages/client/components/blog/BlogPostStatus.tsx, resources/style.css
=> add post status tag to non-public posts

packages/client/components/LandingPageFrame.tsx, resources/style.css
=> Add login link to nav

packages/client/components/blog/BlogPageNavbar.tsx
I read the "don't merge until fixing" right when I clicked the button. Whoops.
=> Props fix for navbar

packages/client/components/blog/BlogPostContent.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/768).
* #769
* __->__ #768
=> Fix blog crash on reload

packages/client/components/blog/BlogPageGlimmer.tsx, packages/client/components/blog/BlogPostContent.tsx, packages/client/pages/BlogPage.tsx, resources/style.css
The contents of a blog post will glimmer until they're finished loading.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/769).
* __->__ #769
* #768
=> Add glimmer to blog posts.

resources/style.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/779).
* __->__ #779
* #778
* #777
=> blog image style fix

packages/client/components/LandingPageHero.tsx
=> Update homepage copy

experimental/randallb/s.ipynb, infra/jobRunner/jobRunner.ts, packages/bfDb/models/BfMediaNodeTranscript.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/799)
=> Fix ingestion back to status quo

packages/bfDb/models/BfGoogleDriveResource.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/800)
=> Fix example

infra/jobRunner/jobRunner.ts, packages/bfDb/models/BfGoogleDriveResource.ts, packages/bfDb/models/BfMediaNodeTranscript.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/803).
* __->__ #803
* #802
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/803)
=> Simplify ingestion to ensure consistency

.github/workflows/nix-github-actions.yml, infra/bff/friends/ci.bff.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/816)
=> Disable ci more elegantly

.github/workflows/nix-github-actions.yml
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/817)
=> Only run push gh actions on main

infra/jobRunner/jobRunner.ts, infra/jobRunner/worker.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/819)
=> Make workers work again

packages/graphql/types/BfGraphQLSavedSearch.ts
=> fix fake data to match new type

packages/bfDb/models/BfSavedSearch.ts, packages/bfDb/utils.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/825).
* __->__ #825
* #824
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/825)
=> Remove artificial delay from search result generation

packages/graphql/types/BfGraphQLSavedSearch.ts
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/826)
=> Feature flag the fake search result

packages/bfDb/models/BfSavedSearchResult.ts, packages/client/components/clipsearch/ClipEditButton.tsx, packages/client/components/clipsearch/ClipEditModal.tsx, packages/client/components/clipsearch/DownloadClipButton.tsx, packages/client/components/clipsearch/SearchResult.tsx, packages/client/deps.ts, packages/graphql/types/BfGraphQLSavedSearchResult.ts, packages/graphql/types/GraphQLMedia.ts, packages/graphql/types/mod.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/829).
* __->__ #829
* #828
* #827
- - -
This pull request can be reviewed on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/829)
=> Frontend for search results

packages/bfDb/models/BfSavedSearchResult.ts, packages/client/components/clipsearch/ClipEditModal.tsx, packages/client/components/clipsearch/ClipWord.tsx, packages/client/components/clipsearch/WordMenu.tsx, resources/style.css
Summary:
Test Plan:
https://github.com/user-attachments/assets/8f565872-975f-44b5-86a5-07d43c523f6e
=> clip edit ui

packages/bfDs/Demo.tsx
=> add hex values to color palette in demo

packages/client/components/clipsearch/ClipEditModal.tsx, packages/client/components/clipsearch/ClipWord.tsx, packages/client/components/clipsearch/EditWordMenu.tsx, packages/client/components/clipsearch/WordMenu.tsx, resources/style.css
=> UI for in and out points and word editing

packages/__generated__/ClipEditButton_bfSavedSearchResult.graphql.ts, packages/__generated__/ClipSearchPageQuery.graphql.ts, packages/__generated__/SearchResultsSubscription.graphql.ts, packages/client/components/clipsearch/ClipEditButton.tsx, packages/client/components/clipsearch/ClipEditModal.tsx, packages/client/components/clipsearch/ClipWord.tsx, packages/client/components/clipsearch/EditWordMiniModal.tsx, packages/client/components/clipsearch/TrimMenu.tsx, packages/client/components/clipsearch/WordMenu.tsx, packages/client/components/clipsearch/WordMenuItem.tsx, packages/client/contexts/ClipEditModalContext.tsx, packages/types/transcript.ts, resources/style.css
Summary:
Test Plan:
https://github.com/user-attachments/assets/493ec01f-412f-4300-8558-c067ce7b5fec
=> FE logic for clip editing

packages/client/components/clipsearch/ClipWord.tsx, packages/client/contexts/ClipEditModalContext.tsx
=> ui fix no console logs

packages/client/contexts/AppStateContext.tsx
Summary: feature flags stay toggled across refresh
Test Plan:
=> persistent feature flag setting

experimental/justin/queryTargetsConnectionForGraphQL.ipynb, packages/__generated__/SettingsPageQuery.graphql.ts, packages/__generated__/WatchFolderListPaginationQuery.graphql.ts, packages/__generated__/WatchFolderList_bfOrganization.graphql.ts, packages/bfDb/bfDb.ts, packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/coreModels/BfNode.ts, packages/client/components/settings/WatchFolderList.tsx, packages/graphql/types/BfGraphQLCollection.ts, packages/graphql/types/BfGraphQLMedia.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/852).
* __->__ #852
* #851
* #849
* #848
=> update watched folders query to use collection

deno.jsonc, replit.nix
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/891)
=> Freeze the lock file and rm postgres again

infra/internalbf.com/client/contexts/RouterContext.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/893)
=> more bugfixes

infra/internalbf.com/client/contexts/RouterContext.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/895)
=> will i ever learn

packages/bfDb/models/BfSavedSearchResult.ts, packages/client/components/clipsearch/SearchResults.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/899)
=> Fix random console errors

packages/bfDb/utils.ts
Summary: change table name from `bfDb` to `bfdb`
Test Plan:
=> fix db:reset

packages/client/components/App.tsx, packages/client/contexts/AppEnvironmentContext.tsx, packages/client/pages/AgentPage.tsx, packages/clientRenderer/clientRenderer.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/898)
=> Agent page boilerplate

experimental/randallb/rundown.ipynb
=> Spec for "time based linear media"

packages/client/components/LoginForm.tsx
=> Fix a google login race condition
