bolt-foundry/bolt-foundry

- flake.lock
- flake.nix
Update sapling version
requires updating the bf base replit path b/c of the flake update
Summary:
Updates sapling version by moving it to unstablepkgs
Test Plan:
```
~/update-sapling/bolt-foundry$ sl --version
Sapling 0.2.20231113
(see https://sapling-scm.com/ for more information)
~/update-sapling/bolt-foundry$ kill 1
~/update-sapling$ sl --version
Sapling 0.2.20240116
(see https://sapling-scm.com/ for more information)
```
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/31)
> Update sapling version

- docs/developing-on-replit.md
- infra/bff/friends/commit.bff.ts
Changes bff init to bff commit
Summary:
This command is really best served when you're committing.
Since our codebase is small enough, it'll pull main and goto it allowing you to pre-emptively fix any merge conflicts before committing.
Test Plan:
```sh
bff commit
```
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/32)
> Changes bff init to bff commit

- infra/bff/friends/deploy.bff.ts
Move deploy to the proper spot
Summary:
Also moves the github confirmation step earlier and fails if the gh token isn't found.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/39)
> Move deploy to the proper spot

- infra/bff/friends/commit.bff.ts
Add Bootcamp Task
Summary:
Task for preventing an error if a github user doensn't have a display name when committing.
Test Plan:
fish emoji
> Add Bootcamp Task

- infra/bff/friends/commit.bff.ts
Fix bff commit
Summary:
Replit disabled their old style ssh gateway.
Test Plan:
`bff commit` on any repl
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/100)
> Fix bff commit

- infra/bff/friends/build.bff.ts
- infra/bff/friends/nix.bff.ts
Deploy fewer dependencies to prod
Summary:
This should shrink the amount of dependencies that make it to production deployments
Test Plan:
`bff nix:deploy` should break sapling
`bff nix` should fix it
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/107)
> Deploy fewer dependencies to prod

- lib/ffmpegInterface.ts
- lib/googleDriveApi.ts
- packages/bfDb/models/BfNodeGoogleDriveFile.ts
Add ingestion -> ffmpeg stuff
Summary:
Downloads videos from google drive to the replit in /tmp and runs them through ffmpeg, outputting them to /tmp/bff/x.mp4
Test Plan:
https://github.com/bolt-foundry/bolt-foundry/assets/448694/0c83a758-5270-4148-be2a-06489f991b00
> Add ingestion -> ffmpeg stuff

- flake.nix
Add default packages to shell env
Summary:
This ensures the shell env and the vscode env have all packages.
Test Plan:
https://replit.com/t/bolt-foundry/xjbbzx/repls/fixathon etc.
> Add default packages to shell env

- lib/ffmpegInterface.ts
Write video data to the build directory
Summary:
For now, replit has a bug where if you store to /tmp it can die... so we're storing it in our build directory.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/128)
> Write video data to the build directory

- infra/bff/friends/commit.bff.ts
- lib/_readme.md
- packages/client/lib/_readme.md
- packages/lib/_readme.md
fix gh no display name
Summary:
Allows user to commit even if they don't have a display name on gh. Shows warning message on console to add display name.
Test Plan:
🥑
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/114).
* __->__ #114
* #113
> fix gh no display name

- deps.ts
- infra/build/bffEsbuild.ts
- infra/graphql/graphql.ts
- packages/bfDb/classes/BfModel.ts
Remove log spew
Summary:
Removes a lot of rando log spew from the console. Building right now is still erroring, but we can figure that out later.
Test Plan:
run, check logs. Change env var LOG_LEVEL if you want.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/132).
* #133
* __->__ #132
* #131
> Remove log spew

- deps.ts
Clean up logger
Summary:
Previously, we'd have a ton of log spew. Now, devs should use logger.debug for "extended info" and logger.trace for "wtf is happening right now" logging.
Test Plan:
next diff will work
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/131).
* #133
* #132
* __->__ #131
> Clean up logger

- infra/bff/friends/db.bff.ts
Add a util to reset db stuff
Summary:
Test Plan:
`bff db:reset` should only work in dev.
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/156)
> Add a util to reset db stuff

- experimental/randallb/watcher/addClipToNotion.ts
- experimental/randallb/watcher/ingest.ts
- experimental/randallb/watcher/notionApi.ts
- experimental/randallb/watcher/watcher.ts
add notion task on upload success
Summary:  a task gets made in notion for the chuncked file and notifies in Discord
Test Plan:<img width="957" alt="Screenshot 2024-06-20 at 12 57 51 PM" src="https://github.com/bolt-foundry/bolt-foundry/assets/87879951/74ae1bd4-cda2-46a1-98c2-0b4beb6a8667">
> add notion task on upload success

- flake.nix
- replit.nix
Remove packages from replit.nix
Summary:
Had to remove a bunch of pkgs here b/c they show up in the size reported to replit or something.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/168)
> Remove packages from replit.nix

- packages/web/web.ts
Throw error if you're not logged in when accessing the graphql endpoint
Summary:
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/171)
> Throw error if you're not logged in when accessing the graphql endpoint

- packages/web/web.ts
Proxy old graphql so we can run the ingest script through .com
Summary:
.com proxy for ingest script
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/172)
> Proxy old graphql so we can run the ingest script through .com

- aws/client/components/SettingsForm.tsx
- aws/client/components/SettingsProjectSidebar.tsx
Add draft setting preset check
If you change a setting, it removes the preset name from the drop menu; however, if you change it back, it will show the preset once again.
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/201).
* __->__ #201
* #200
* #199
> Add draft setting preset check

- aws/client/lib/BFRenderer.ts
Swap to old audio thing now that we're using rbServe™
Summary:
We originally hacked in this way of making audio b/c it takes forever to download the original video... but now we've moved our setup to rbServe™ so we shouldn't have this issue anymore. This method is much more reliable to extract audio which is synced.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/204)
> Swap to old audio thing now that we're using rbServe™

- aws/client/lib/BFRenderer.ts
Disable font loading
Summary:
Since we're downloading on the mac studio which we can guarantee has the correct fonts, disable font loading and only preload images.
Test Plan:
> Disable font loading

- infra/bff/friends/commit.bff.ts
- packages/bfDb/models/BfOrganization.ts
Make BfOrganization own accounts instead of the account creating it
Summary:
This kicks the account problem down the road... accounts today are like half an edge... they don't inherit from bfedge but essentially they work like an edge.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/250).
* __->__ #250
* #249
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/250)
> Make BfOrganization own accounts instead of the account creating it

- infra/__generated__/PlaygroundPageMutation.graphql.ts
- infra/__generated__/_graphql_imports.ts
- infra/__generated__/_nexustypes.ts
- infra/graphql/schema.graphql
- infra/graphql/types/IBfPlaygroundMutation.ts
- infra/graphql/types/mod.ts
- infra/internalbf.com/client/components/App.tsx
- infra/internalbf.com/client/pages/PlaygroundPage.tsx
Add Playground to Infra
Summary: Adds a new endpoint, "/colby", to internalbf.com with a corresponding graphql mutation and UI page. The UI is boilerplate for now, just an integration test. Functionality will be added later.
Test Plan: 🦧
> Add Playground to Infra

- thirdParty/daily-vcs-main/js/src/comp-backing-model.js
Fix for crash when rendering text overlays in baseline comp
> VCS: fix text layout for non-span strings

- thirdParty/daily-vcs-main/js/src/loader-base.js
- thirdParty/daily-vcs-main/js/vcs-batch-runner.js
Catch React errors early for VCS batch runner and print out the stack trace.
> VCS batch runner: print out full error and exit

- .gitignore
- flake.lock
- flake.nix
- packages/vcs/cli-render/bf-vcscut-tools/install_and_build_vcsrender.sh
Set up server vcs builds
Summary:
Will work on a mac probably™. Requires brew. Needs to be nixified if we want it to be easier to use on replit.
Test Plan:
```sh
cd packages/vcs/cli-render/bf-vcscut-tools
./install_and_build_vcsrenderer.sh
npm run render ../example-data/short_clip.mp4
```
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/330)
> Set up server vcs builds

- infra/bff/friends/boot.bff.ts
Summary:
deals with node_modules having absolute symlinks from Deno.
Test Plan:
- - -
This pull request can be reviewed on [<img src="https://gitcontext.com/logo/GitContextButton.svg" height="32" align="absmiddle" alt="GitContext.com"/>](https://gitcontext.com/app/prs/github/bolt-foundry/bolt-foundry/528)
> rm node_modules on repl boot

- infra/bff/friends/boot.bff.ts
- infra/bff/friends/populate.bff.ts
- infra/bff/friends/transcribe.bff.ts
- packages/bfDb/classes/BfModel.ts
- packages/bfDb/coreModels/BfEdge.ts
- packages/bfDb/coreModels/BfNode.ts
- packages/bfDb/models/BfClip.ts
- packages/bfDb/models/BfGoogleAuth.ts
- packages/bfDb/models/BfGoogleDriveResource.ts
- packages/bfDb/models/BfJob.ts
- packages/bfDb/models/BfOrganization.ts
- packages/bfDb/models/BfPerson.ts
- packages/bfDb/utils.ts
- packages/graphql/types/BfGraphQLClip.ts
- packages/graphql/types/BfGraphQLGoogleAuth.ts
- packages/graphql/types/BfGraphQLGoogleDriveResource.ts
- Summary:
- `BfNode` is the recommended way to interact with everything inside of `BfDb`. Every part of the graph should be a `BfNode` and not a `BfModel`. Relatedly, with few exceptions every Node should be created from a source BfNode. That means, the primary method for creating models should now be `bfNodeInstance.createTargetNode`, **NOT** `BfModel.create`.
- This also has some other upsides, notably it's impossible to mess up current viewer. Since every node will already have a current viewer, it seems reasonable that instead of having to specify one every time you create a new node, it'll just inherit the current viewer that loaded the original source node.
- Deep deletes will likely happen automatically whenever a target node has no source nodes, which would cascade down a tree …
> Rename BfModel.create to a __DANGEROUS__ prefix, recommend instead people use bfNode.createTargetNode

- packages/client/components/LandingPageClipCollection.tsx
- packages/client/components/LandingPageHero.tsx
- packages/client/components/LandingPageMission.tsx
- packages/client/components/LandingPageSetUpMeeting.tsx
- packages/client/components/LandingPageTestimonials.tsx
- packages/client/pages/LandingPage.tsx
- resources/style.css
Removes inline react styling as well as marketing styling from the landing page. All styles for the landing page are in the css file under "landing-page-x".
Also some minor layout changes for the page.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/579).
* __->__ #579
* #578
> CSS Refactor for Landing Page

- packages/bfDb/bfDb.ts
Summary:
Seems like a good idea to let the models control their own batch size... ie BfMediaNodeTranscript will always be pretty huge and doing 4 at a time is appropriate, but others are probably tiny, so they could have much larger batch sizes. Also, retrying with exponential backoff could also be a good idea.
Test Plan:
> Fix batching so it defaults to smaller batch sizes

- infra/bff/friends/db.bff.ts
- packages/bfDb/bfDb.ts
- packages/bfDb/coreModels/BfEdge.ts
- packages/bfDb/utils.ts
Summary:
Makes it so all queries go through the same path to avoid small bugs. (DRY)
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/767).
* #770
* __->__ #767
* #766
* #765
> Unify db query methods into the same logical fw

- deps.ts
Summary: Instead of
`long/file/path/that/takes/up/space.tsx INFO: The only thing you care about`
Format like this:
`↱  long/file/path/that/takes/up/space.tsx:33
INFO: The only thing you care about`
Of note, the file path is dim so it doesn't stand out and it has the line number after the filename. And logs that are back to back are collated under one path instead of printing the same path every time
Test Plan:
> Reformat logger
